### ISSUE TITLE
In android Exception: Unable to retrieve the current playback position

### ISSUE THREAD

**Issue by ShivarajYadagiri** [Sunil9162/ivs_broadcaster#1]
I'm not able to play the live video In Android, getting the below exception.

MissingPluginException(No implementation found for method position on channel ivs_player)
E/flutter (14698): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Unable to retrieve the current playback position [Get Position]
E/flutter (14698): #0      IvsPlayerMethodChannel.getPosition (package:ivs_broadcaster/Player/ivs_player_method_channel.dart:166:7)

**Comment by Sunil9162** [comment]
New version with added ivs player is now on pub.dev
